-- 009-intake-queue-assign-forward.sql
--
-- Two things staff were missing on the Pre-Intake Queue, both before a bed
-- exists: who is working a lead, and a way to hand it off. Both are internal
-- only, on purpose - nothing here emails or otherwise ships anyone's health,
-- substance-use, or contact details anywhere. "Forward" is a same-page status
-- flag plus a short number a case manager can be told over the phone or in
-- person ("check queue #1042"), never a data export.
--
-- Safe to re-run: every statement is guarded.

-- Short, stable per-row number for verbal/internal reference. Generated by
-- Postgres on insert (existing rows get one too), never reused, never shown
-- to the public - this is not a case number in any legal sense, just a way
-- to say "that one" without repeating a name over the phone.
create sequence if not exists public.intake_queue_no_seq;

alter table public.intake_requests
  add column if not exists queue_no bigint default nextval('public.intake_queue_no_seq');

update public.intake_requests set queue_no = nextval('public.intake_queue_no_seq') where queue_no is null;

alter table public.intake_requests
  add column if not exists case_manager text;

alter table public.intake_requests
  add column if not exists forwarded_to text;

alter table public.intake_requests
  add column if not exists forwarded_at timestamptz;

comment on column public.intake_requests.queue_no is
  'Sequential internal reference number, assigned on insert. For verbal/internal use only - not exposed publicly, not a legal case number.';
comment on column public.intake_requests.case_manager is
  'Who is working this lead, set before any bed or admission exists. Independent of residents.case_manager, which takes over after Admit.';
comment on column public.intake_requests.forwarded_to is
  'Case manager (or team) this request was handed off to. Internal status only - forwarding never emails or exports the request.';
comment on column public.intake_requests.forwarded_at is
  'When it was forwarded. Null means still sitting with whoever first took the call.';
